app: github-action-demo

service: simple-rest-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'development'}
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:service}-${self:provider.stage}
  region: ${env:AWS_REGION, 'us-west-2'}
  memorySize: 128
  timeout: 30
  deploymentBucket:
    name: simple-rest-service-${self:provider.stage}
    serverSideEncryption: AES256
    blockPublicAccess: true
  environment:
    LOG_LEVEL: debug
# you can add packaging information here
package:
  exclude:
    - tests/**
plugins:
  - serverless-deployment-bucket
  - serverless-plugin-typescript
  - serverless-offline

functions:
  trigger:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get
