name: Deploy main branch

on:
  workflow_dispatch:
  push:
    branches:
      - release/rest-lambda

env:
  _ENVIRONMENT: development
  _REPOSITORY_NAME: github-action-nodejs-serverless

jobs:
  DeployServerless:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: "ubuntu-latest-node-full-v16-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ubuntu-latest-node-full-v16-
      - name: Install Dependencies
        run: npm install
      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
