name: Deploy test branch

on:
  workflow_call: # If a default parameter is not set, the default value of the input is false for a boolean, 0 for a number, and "" for a string.
    inputs:
      username:
        description: 'A username should be passed from the caller workflow'
        required: true
        type: string
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  github-action-test:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
